Remove SIMD_FUNC for readability
Clean ASM_AVX2/cdef_block_simd.c

Remove dead head files

They are never used after cleaning cdef_block_simd.c.

Change CDEF_VERY_LARGE from 30000 to 16384

to facilitate SIMD optimization.

Add eb_cdef_filter_block_8x8_16_avx512()

About 20% faster than eb_cdef_filter_block_8x8_16_avx2().

Temporally activate AVX512 code

Fix gcc build "undefined reference to _mm256_cvtsi256_si32"

Add search_one_dual_avx512()

First updated search_one_dual_avx2(), and got 40% faster.
Then add search_one_dual_avx512(), and got 30% - 50% faster.
Speed totally doubled than old avx2.

Revert the change to search_one_dual_avx2()

which needs target feature avx512vl.

So the speed of search_one_dual_avx2() won't improve.

Revert "Temporally activate AVX512 code"

This reverts commit 512b4b1497c7d2935cfcb5d167879a98d4998a4e.

Fix SIGSEGV caused by memory alignment